# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.srcs/sources_1/bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_1/subsystem_1_axi_interconnect_0_imp_auto_pc_1.xci
# IP: The module: 'subsystem_1_axi_interconnect_0_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_1/subsystem_1_axi_interconnect_0_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_interconnect_0_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.srcs/sources_1/bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_1/subsystem_1_axi_interconnect_0_imp_auto_pc_1.xci
# IP: The module: 'subsystem_1_axi_interconnect_0_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_1/subsystem_1_axi_interconnect_0_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_interconnect_0_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
