# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.srcs/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0.xci
# IP: The module: 'subsystem_1_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.srcs/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0.xci
# IP: The module: 'subsystem_1_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'subsystem_1_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
