# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/my_simple_uart_0.xci
# IP: The module: 'my_simple_uart_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/constrs_1/imports/constrs/uart_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_simple_uart_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/constrs_1/new/uart_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_simple_uart_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/my_simple_uart_0.xci
# IP: The module: 'my_simple_uart_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/constrs_1/imports/constrs/uart_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_simple_uart_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/vivado/ug1119-vivado-creating-packaging-ip-design/ug1119-vivado-creating-packaging-ip-design/lab_1/my_simple_uart_0/constrs_1/new/uart_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_simple_uart_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
