# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_ipi.xdc

# Block Designs: bd/subsystem_1/subsystem_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1 || ORIG_REF_NAME==subsystem_1} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_quad_spi_0_0/subsystem_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_quad_spi_0_0 || ORIG_REF_NAME==subsystem_1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_iic_0_0/subsystem_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_iic_0_0 || ORIG_REF_NAME==subsystem_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_uartlite_0_0/subsystem_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_uartlite_0_0 || ORIG_REF_NAME==subsystem_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_bram_ctrl_0_0/subsystem_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==subsystem_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_intc_0_0/subsystem_1_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_intc_0_0 || ORIG_REF_NAME==subsystem_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_xbar_0/subsystem_1_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_0/subsystem_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_0 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_bram_ctrl_0_bram_0/subsystem_1_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==subsystem_1_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_xlconcat_0_0/subsystem_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_xlconcat_0_0 || ORIG_REF_NAME==subsystem_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_xlconstant_0_0/subsystem_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_xlconstant_0_0 || ORIG_REF_NAME==subsystem_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_0/subsystem_1_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_1/subsystem_1_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_2/subsystem_1_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/subsystem_1/ip/subsystem_1_axi_interconnect_0_imp_auto_pc_3/subsystem_1_axi_interconnect_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_3 || ORIG_REF_NAME==subsystem_1_axi_interconnect_0_imp_auto_pc_3} -quiet] -quiet

# XDC: c:/Users/User/vivado/ug995_tutorial/ug995_tutorial.gen/sources_1/bd/subsystem_1/subsystem_1_ooc.xdc
